### PR TITLE
 Adding a way to configure the containers address

### PR DESCRIPTION
**Pull request by fr34kyn01535**

### CODE REVIEW

**Review by muehre — COMMENTED** [review]
I will have a look on Sunday :)

**Comment by fr34kyn01535** [comment]
I couldn't build the project,.. had some issues including the stats library with the pom supplied. If you could rebuild and release it afterwards i'd be happy :D

**Comment by muehre** [comment]
Ok got the idea, but why do you need static ip configs? Is there any issue with the discovery from the docker network?

**Comment by fr34kyn01535** [comment]
It adds 0.0.0.0 as ip to the other servers which wont work. I am hosting it in Rancher, the servers are all in the same network and the dns name for the servers could be added as environment variable to be accesible that way. All servers could listen on the default port. There is no need to make the servers publicly accesible on the host network.

________________________________
Von: Alexander Mührenberg <notifications@github.com>
Gesendet: Donnerstag, 20. September 2018 20:46
An: DockerizedCraft/Core
Cc: Sven Mawby; Author
Betreff: Re: [DockerizedCraft/Core] Adding a way to configure the containers address (#1)


Ok got the idea, but why do you need static ip configs? Is there any issue with the discovery from the docker network?

**Comment by jnijland** [comment]
Seems like this is the latest active reaction to DockerizedCraft. I've been testing it for a while, but whatever I do and wherever I run it, I receive the same error. 

```Default server or group not defined``` 

I saw this pull request, and it made me very happy because I tried to use the plugin on a Rancher cluster, but I kept on receiving this error. But even though I've compiled this plugin with this code, it still doesn't work. Also, using it on a normal Docker Swarm via CLI doesn't work. 

Maybe you have a tip?

**Comment by fr34kyn01535** [comment]
@jnijland GitHub doesnt work that way, you should create a new issue for that. I didnt do any more attempts, it seems not to build ootb in intellij or netbeans. Do you have a server setup as default lobby server in bungee cord? If you cant find a solution please open a separate issue.

**Comment by jnijland** [comment]
I've already added a new issue, my bad. Used to working on GitLab in my company.
________________________________
Van: Sven Mawby <notifications@github.com>
Verzonden: zaterdag 22 september 2018 22:17
Aan: DockerizedCraft/Core
CC: Jurrian Nijland; Comment
Onderwerp: Re: [DockerizedCraft/Core] Adding a way to configure the containers address (#1)


Github doesnt work that way, you should create a new issue for that. I didnt do any more attempts, it seems not to build ootb in intellij or netbeans. Do you have a server setup as default lobby server in bungee cord? If you cant find a solution please open a separate issue.

**Comment by muehre** [comment]
Hey @jnijland 
I added you to the DockerizedCraft Team, feel free to participate to this Project 👍

**Comment by fr34kyn01535** [comment]
Could this be merged now?

**Comment by fr34kyn01535** [comment]
> Could this be merged now?

?

**Pull request closed without merging**
