### PR TITLE
Refreshing dependencies + changing SERVER_TYPE to TYPE

### PR DESCRIPTION
**Pull request by ArnaudLier**
Hello, I really love this projet so please, don't give up on it.

### CODE REVIEW

**Comment by muehre** [comment]
Hey @ZeProf2Code. I already answered your E-Mail.
As I do not develop any minecraft plugins anymore I wont maintain this Project anymore.
If you want to take over feel free to do so ;)

**Comment by ArnaudLier** [comment]
@muehre Okay, thank you ;)

**Comment by ArnaudLier** [comment]
@muehre Note if you didn't know: I don't have access to write permissions on the repository.

**Comment by muehre** [comment]
@ZeProf2Code now you do ;)

**Pull request merged**
